/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    ErrorBoundary: typeof import('./src/components/error/ErrorBoundary.vue')['default']
    ErrorFallBack: typeof import('./src/components/error/ErrorFallBack.vue')['default']
    HelloWorld: typeof import('./src/components/common/HelloWorld.vue')['default']
    PostComment: typeof import('./src/components/post/PostComment.vue')['default']
    PostDetail: typeof import('./src/components/post/PostDetail.vue')['default']
    PostList: typeof import('./src/components/post/PostList.vue')['default']
    PostPaging: typeof import('./src/components/post/PostPaging.vue')['default']
    PostSearch: typeof import('./src/components/post/PostSearch.vue')['default']
    PostWrite: typeof import('./src/components/post/PostWrite.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpinnerLoading: typeof import('./src/components/loading/SpinnerLoading.vue')['default']
  }
}
